name: Build Image
on:
  push:
    branches: [ main ]

jobs:  
  push_to_registry:
    name: Push image to GitHub Package Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.actor }}/wagi-dotnet
          tags: |
            type=sha
          flavor: |
            latest=true
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: .github/release-image/Dockerfile
          context: ./Hippo/bin/Release/net5.0/linux-x64/publish
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}